package com.tranhienchuong.nomad.core.designsystem

import androidx.compose.ui.graphics.Color

val NomadSlateBlue = Color(0xFF2C3E50)
val NomadTeal = Color(0xFF00A86B)
val NomadEmerald = Color(0xFF10B981)
val NomadAmber = Color(0xFFF59E0B)
val NomadCoral = Color(0xFFEF4444)

internal val NomadLightPrimary = Color(0xFF2C3E50)
internal val NomadLightOnPrimary = Color(0xFFFFFFFF)
internal val NomadLightPrimaryContainer = Color(0xFFE2E8F0)
internal val NomadLightOnPrimaryContainer = Color(0xFF1E293B)
internal val NomadLightSecondary = Color(0xFF00A86B)
internal val NomadLightOnSecondary = Color(0xFFFFFFFF)
internal val NomadLightSecondaryContainer = Color(0xFFD1FAE5)
internal val NomadLightOnSecondaryContainer = Color(0xFF065F46)
internal val NomadLightBackground = Color(0xFFF8FAFC)
internal val NomadLightSurface = Color(0xFFFFFFFF)
internal val NomadLightOutline = Color(0xFFCBD5E1)
internal val NomadLightError = Color(0xFFDC2626)

internal val NomadDarkPrimary = Color(0xFF94A3B8)
internal val NomadDarkOnPrimary = Color(0xFF0F172A)
internal val NomadDarkPrimaryContainer = Color(0xFF334155)
internal val NomadDarkOnPrimaryContainer = Color(0xFFE2E8F0)
internal val NomadDarkSecondary = Color(0xFF34D399)
internal val NomadDarkOnSecondary = Color(0xFF064E3B)
internal val NomadDarkSecondaryContainer = Color(0xFF065F46)
internal val NomadDarkOnSecondaryContainer = Color(0xFFA7F3D0)
internal val NomadDarkBackground = Color(0xFF0F172A)
internal val NomadDarkSurface = Color(0xFF1E293B)
internal val NomadDarkOutline = Color(0xFF475569)
internal val NomadDarkError = Color(0xFFF87171)

val NomadBadgeGradient1 = listOf(Color(0xFF3B82F6), Color(0xFF1D4ED8))
val NomadBadgeGradient2 = listOf(Color(0xFF10B981), Color(0xFF047857))
val NomadBadgeGradient3 = listOf(Color(0xFF8B5CF6), Color(0xFF6D28D9))
val NomadBrandGradient = listOf(Color(0xFF2C3E50), Color(0xFF00A86B))
